"""Add migration message here

Revision ID: 1a02c459ea6c
Revises: 4ee1fec7a920
Create Date: 2025-03-30 00:08:09.611768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a02c459ea6c'
down_revision = '4ee1fec7a920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_time', sa.Time(), nullable=True),
    sa.Column('admin_review_time', sa.Time(), nullable=True),
    sa.Column('send_time', sa.Time(), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('articles_json', sa.Text(), nullable=True),
    sa.Column('selected_json', sa.Text(), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selected_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['article_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('selected_article')
    op.drop_table('article_batch')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
